"""
Build the pooled SI table for the positive-control blinding experiments.

Rows are the six blinding levels; column groups are the two single-step ("direct")
sweeps, which are the ones all conclusions rest on:

  BP/direct : 45 Wikipedia boiling points, all six levels
  AW/direct : 41 IUPAC atomic weights, levels 1-4 only (the Agnostic levels are
              undefined there -- each element occurs exactly once)

Per group: Pearson |r| against the level's own target, the 3-significant-digit
exact-match rate (count-pooled over models and runs), and the retention ratio
R21 = m2/m1 in the convention of Tables S1/S2.

The two benchmark-prompt ("analysis") sweeps are deliberately NOT in this table.
Their weighted-average instruction suppresses exact reproduction, so their rates
are not comparable to the direct ones; the single Level-1 pair needed to quantify
that suppression is quoted in the SI text, and the full numbers stay in
blinding_control_permodel{,_atomicweights}.csv.

Run analyze_blinding_control.py for direct and atomic_direct first.

Usage:
    python make_blinding_control_si_table.py
"""
import os

import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))

SWEEPS = [
    ("blinding_control_permodel_direct.csv", "BP/direct"),
    ("blinding_control_permodel_atomicweights_direct.csv", "AW/direct"),
]

LEVEL_ORDER = [
    "1 Specific / original", "2 Specific / transformed",
    "3 Generic / original", "4 Generic / transformed",
    "5 Agnostic / original", "6 Agnostic / transformed",
]
LEVEL_TEX = [
    "1 Specific, orig.", "2 Specific, transf.",
    "3 Generic, orig.", "4 Generic, transf.",
    "5 Agnostic, orig.", "6 Agnostic, transf.",
]


def load():
    frames = {}
    for fname, label in SWEEPS:
        path = os.path.join(HERE, fname)
        if not os.path.exists(path):
            raise SystemExit(f"missing {fname} -- run analyze_blinding_control.py first")
        frames[label] = pd.read_csv(path)
    return frames


def main():
    frames = load()
    rows = []
    for lvl, tex in zip(LEVEL_ORDER, LEVEL_TEX):
        cells = []
        for _, label in SWEEPS:
            sub = frames[label][frames[label].level == lvl]
            if not len(sub):
                cells += ["--", "--", "--"]
                continue
            r = sub.r.mean()
            hits, tot = sub.m3_hits.sum(), sub.m3_total.sum()
            m1, m2 = sub.m1.sum(), sub.m2_cnt.sum()
            cells += [
                f"{r:.0f}" if pd.notna(r) else "--",
                f"{100 * hits / tot:.1f}" if tot else "--",
                f"{100 * m2 / m1:.0f}" if m1 else "--",
            ]
        rows.append(f"{tex} & " + " & ".join(cells) + r" \\")

    out = os.path.join(HERE, "blinding_control_si_table.tex")
    with open(out, "w", encoding="utf8", newline="\n") as f:
        f.write("% Generated by make_blinding_control_si_table.py -- do not edit by hand.\n")
        f.write("\n".join(rows) + "\n")
    print(f"wrote {os.path.basename(out)}\n")
    print("\n".join(rows))


if __name__ == "__main__":
    main()
